/**
 * Generated by orval v6.23.0 🍺
 * Do not edit manually.
 * Tippecc WIS
 * Your project description
 * OpenAPI spec version: 1.0.0
 */
import type { ClimateParameter } from './climateParameter';

export type ClimateFunctionDetailParamsDict = { [key: string]: ClimateParameter };
