/**
 * Generated by orval v6.23.0 🍺
 * Do not edit manually.
 * Tippecc WIS
 * Your project description
 * OpenAPI spec version: 1.0.0
 */
import type { ClimateFunctionRequestParamvalueDict } from './climateFunctionRequestParamvalueDict';

export interface ClimateFunctionRequest {
  dataset_list: string[];
  paramvalue_dict: ClimateFunctionRequestParamvalueDict;
}
