/**
 * Generated by orval v6.23.0 🍺
 * Do not edit manually.
 * Tippecc WIS
 * Your project description
 * OpenAPI spec version: 1.0.0
 */
import type { ClimateFunctionDetailDatasetDict } from './climateFunctionDetailDatasetDict';
import type { ClimateFunctionDetailParamsDict } from './climateFunctionDetailParamsDict';

export interface ClimateFunctionDetail {
  dataset_dict: ClimateFunctionDetailDatasetDict;
  readonly id: number;
  params_dict: ClimateFunctionDetailParamsDict;
}
