/**
 * Generated by orval v6.25.0 🍺
 * Do not edit manually.
 * Tippecc WIS
 * Tippecc WIS is a web-based information system in development with a generic workflow for climate indices calculation
 * OpenAPI spec version: 1.0.0
 */
import type { ClimateFunctionRequestParamvalueDict } from './climateFunctionRequestParamvalueDict';

export interface ClimateFunctionRequest {
  aoi: number[];
  dataset_list: string[];
  file_id_list: string[];
  paramvalue_dict: ClimateFunctionRequestParamvalueDict;
}
