/**
 * Generated by orval v6.25.0 🍺
 * Do not edit manually.
 * Tippecc WIS
 * Your project description
 * OpenAPI spec version: 1.0.0
 */

export type ClimateFunctionRequestParamvalueDict = {[key: string]: {}};
