/**
 * Generated by orval v6.25.0 🍺
 * Do not edit manually.
 * Tippecc WIS
 * Tippecc WIS is a web-based information system in development with a generic workflow for climate indices calculation
 * OpenAPI spec version: 1.0.0
 */
import type { ClimateFunctionDetailDatasetDict } from './climateFunctionDetailDatasetDict';
import type { ClimateFunctionDetailParamsDict } from './climateFunctionDetailParamsDict';

export interface ClimateFunctionDetail {
  dataset_dict: ClimateFunctionDetailDatasetDict;
  readonly id: number;
  params_dict: ClimateFunctionDetailParamsDict;
}
