/**
 * Generated by orval v6.23.0 🍺
 * Do not edit manually.
 * Tippecc WIS
 * Your project description
 * OpenAPI spec version: 1.0.0
 */

export interface ClimateDataset {
  desc: string;
  filter_word: string;
  name: string;
  readonly optional: boolean;
}
