/**
 * Generated by orval v6.25.0 🍺
 * Do not edit manually.
 * Tippecc WIS
 * Tippecc WIS is a web-based information system in development with a generic workflow for climate indices calculation
 * OpenAPI spec version: 1.0.0
 */

export interface ClimateFunction {
  description: string;
  readonly id: number;
  name: string;
}
