/**
 * Generated by orval v6.23.0 🍺
 * Do not edit manually.
 * Tippecc WIS
 * Your project description
 * OpenAPI spec version: 1.0.0
 */

export interface ClimateParameter {
  datatype: string;
  desc: string;
  input_list: string[];
  name: string;
  readonly optional: string;
  unit_list: string[];
}
