/**
 * Generated by orval v6.25.0 🍺
 * Do not edit manually.
 * Tippecc WIS
 * Tippecc WIS is a web-based information system in development with a generic workflow for climate indices calculation
 * OpenAPI spec version: 1.0.0
 */

export * from './climateDataset';
export * from './climateFunction';
export * from './climateFunctionDetail';
export * from './climateFunctionDetailDatasetDict';
export * from './climateFunctionDetailParamsDict';
export * from './climateFunctionRequest';
export * from './climateFunctionRequestParamvalueDict';
export * from './climateParameter';
export * from './executeResponse';