# Generated by Django 5.0 on 2023-12-10 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('toolbox', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ClimateIndicesFunction',
        ),
    ]
